### ISSUE TITLE
VeSync not seeing nodes for ISY

### ISSUE THREAD

**Issue by PaulStraten** [simplextech/udi-poly-vesync#1]
I show to be connected to the VeSync node but I do not receive any of the light module nodes (12 of them) when connected.

Error log attached.

[vesync-0021b900fd99-2 (1).txt](https://github.com/simplextech/udi-poly-vesync/files/6117827/vesync-0021b900fd99-2.1.txt)

**Comment by PaulStraten** [comment]
Anyone assigned to this issue?

**Comment by simplextech** [comment]
The log shows nothing useful.

Install details?
Polisy or PGC?
VeSync devices model information.

Capture a log from NS startup and provide that to see if there's any startup errors.

**Comment by PaulStraten** [comment]
The install showed no errors when loading/installing the nodeserver. It "appeared" to process without error.

The nodeserver was attempted from BOTH Polisy **_and_** PGC. It fails from both.

Devices: VeSync Smart Plug by Etekcity, 4 Pack Mini WiFi Outlets, Works with Alexa, Google Home & IFTTT, Remote Control from Anywhere, WiFi Energy Monitoring with Schedule Function, No Hub Required, ETL Listed (purchased on AMAZON)

I stopped the nodeserver (PGC) and started it again. See log attached.

[vesync-0021b900fd99-2 (2).txt](https://github.com/simplextech/udi-poly-vesync/files/6131046/vesync-0021b900fd99-2.2.txt)

**Comment by PaulStraten** [comment]
Additionally, a Universal Devices technical support member was online via a remote session with me and tried installing from PGC as well as Polisy and it failed for him (Brad) also.

**Comment by simplextech** [comment]
> VeSync Smart Plug by Etekcity

NodeServer was developed for the Etekcity light bulbs.  No other products were in scope.

**Comment by PaulStraten** [comment]
So to be clear, the only device this nodeserver will operate with is a "light bulb"? Not any of the many other devices that are available and widely used?

**Comment by simplextech** [comment]
At this time.  Yes.

**Comment by PaulStraten** [comment]
👎

**Comment by PaulStraten** [comment]
Have you decided to add the PLUG modules yet?
