### ISSUE TITLE
VeSync Plug Modules Not Compatible with ISY API?

### ISSUE THREAD

**Issue by PaulStraten** [simplextech/udi-poly-vesync#2]
When I download the Vesync nodeserver and install it on my ISY controller (or Polisy) I only see a Vesync controller and not
 my PLUG modules. I do not have light dimmer switches, only "plug modules". I need these added to your logic please. Will you do that?

**Comment by PaulStraten** [comment]
Any update?

**Comment by simplextech** [comment]
This nodeserver was developed by commission for support of the vesync bulbs.  No other devices are supported or planned to be added.  Feel free to fork the project for your own use.
